AdminOnlineAuction/Models/Entity/Feedback.cs
using AdminOnlineAuction.Models.Global;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;

namespace AdminOnlineAuction.Models.Entity
{
    public class Feedback
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Content { get; set; }
        public int Status { get; set; }
        public DateTime Created { get; set; }
        public IEnumerable<Feedback> GetAll()
        {
            IEnumerable<Feedback> data;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("FeedBack").Result;
            data = response.Content.ReadAsAsync<IEnumerable<Feedback>>().Result;
            return data;
        }
        public Feedback GetById(int id)
        {
            Feedback data;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("FeedBack/" + id).Result;
            data = response.Content.ReadAsAsync<Feedback>().Result;
            return data;
        }
        public Feedback Edit(Feedback c)
        {
            Feedback data;
            HttpResponseMessage response = GlobalVariables.WebApiClient.PutAsJsonAsync("FeedBack", c).Result;
            data = response.Content.ReadAsAsync<Feedback>().Result;
            return data;
        }
    }
}

AdminOnlineAuction/Controllers/FeedbackController.cs
using AdminOnlineAuction.Models.Entity;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminOnlineAuction.Controllers
{
    public class FeedbackController : Controller
    {
        private Feedback feedback;
        public FeedbackController()
        {
            feedback = new Feedback();
        }
        // GET: Feedback
        public ActionResult Index(int? page)
        {
            if (Session["loginAdmin"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            int _page = page ?? 1;
            int _pageSize = 25;
            var data = feedback.GetAll();
            ViewBag.FeedbackData = data.OrderByDescending(x => x.Created).ToPagedList(_page, _pageSize);
            ViewBag.FbCount = data.Where(x=>x.Status==0).Count();
            return View();
        }
        public ActionResult Detail(int id)
        {
           
            var data = feedback.GetById(id);
            if (data.Status == 0)
            {
                data.Status = 1;
                feedback.Edit(data);
            }

            ViewBag.Data = data;
            var dataAllFb = feedback.GetAll();
            ViewBag.FbCount = dataAllFb.Where(x => x.Status == 0).Count();
            return View();
        }
    }
}

AdminOnlineAuction/Views/Feedback/Detail.cshtml
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Feedback</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Feedback</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="row">
        <div class="col-md-3">


            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Folders</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body p-0">
                    <ul class="nav nav-pills flex-column">
                        <li class="nav-item active">
                            <a href="@Url.Action("Index")" class="nav-link">
                                <i class="fas fa-inbox"></i> Inbox
                                <span class="badge bg-primary float-right">@ViewBag.FbCount</span>
                            </a>
                        </li>

                    </ul>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
            <!-- /.card -->
        </div>
        <!-- /.col -->
        <div class="col-md-9">
            <div class="card card-primary card-outline">
                <div class="card-header">
                    <h3 class="card-title">Read Mail</h3>

                   
                </div>
                <!-- /.card-header -->
                <div class="card-body p-0">
                    <div class="mailbox-read-info">
                        <h5>Feedback</h5>
                        <h6>
                            From: @ViewBag.Data.Email
                            <span class="mailbox-read-time float-right">@ViewBag.Data.Created</span>
                        </h6>
                    </div>
                    <!-- /.mailbox-read-info -->
                   
                    <!-- /.mailbox-controls -->
                    <div class="mailbox-read-message">
                        @ViewBag.Data.Content
                    </div>
                    <!-- /.mailbox-read-message -->
                </div>
                <!-- /.card-body -->
                <div class="card-footer bg-white">
                    
                </div>
                <!-- /.card-footer -->
                <div class="card-footer">
                  
                </div>
                <!-- /.card-footer -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

AdminOnlineAuction/Views/Feedback/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Feedback</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Feedback</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Folders</h3>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body p-0">
                    <ul class="nav nav-pills flex-column">
                        <li class="nav-item active">
                            <a href="#" class="nav-link">
                                <i class="fas fa-inbox"></i> Feedback
                                <span class="badge bg-primary float-right">@ViewBag.FbCount</span>
                            </a>
                        </li>
                        
                    </ul>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
           
            <!-- /.card -->
        </div>
        <!-- /.col -->
        <div class="col-md-9">
            <div class="card card-primary card-outline">
                <div class="card-header">
                    <h3 class="card-title">Feedback</h3>

                    <div class="card-tools">

                    </div>
                    <!-- /.card-tools -->
                </div>
                <!-- /.card-header -->
                <div class="card-body p-0">
                    <div class="table-responsive mailbox-messages">
                        <table class="table table-hover table-striped">
                            <tbody>
                                @foreach (var item in ViewBag.FeedbackData)
                                {

                                    <tr>

                                        <td class="mailbox-star">
                                            @if (item.Status == 1)
                                            {
                                                <a href="#"><i class="fas fa-star text-warning"></i></a>
                                            }

                                        </td>
                                        <td class="mailbox-name"><a href="@Url.Action("Detail","Feedback",new { id = item.ID })" >@item.Email</a></td>
                                        <td class="mailbox-subject">
                                            <b>@item.UserName</b>
                                        </td>

                                        <td class="mailbox-date">@item.Created</td>
                                    </tr>
                                }


                            </tbody>
                        </table>
                        <!-- /.table -->
                    </div>
                    <!-- /.mail-box-messages -->
                </div>
                <!-- /.card-body -->
                <div class="card-footer p-0">
                    <div class="mailbox-controls">
                        <!-- Check all button -->
                        <div class="float-right">
                            @Html.PagedListPager((IPagedList)ViewBag.FeedbackData, page => Url.Action("Index", new { page }))
                            <!-- /.btn-group -->
                        </div>
                        <!-- /.float-right -->
                    </div>
                </div>
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>





@section scripts {

    <script>
        $(function () {
            var sss = '@TempData["Success"]';
            var err = '@TempData["errors"]';

            if (sss != '') {
                swal(sss, "Please confirm to continue!", "success");
            }
            if (err != '') {
                swal(err, "...and here's the text!");
            }
            
        });
        

    </script>


}

AdminOnlineAuction/Views/Feedback/_Detail.cshtml
<div class="modal-dialog" role="document">
    <div class="modal-content" style="width:700px;">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Detail:</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <div class="modal-body">
            <h3 class="text-primary"><i class="fas fa-paint-brush"></i> @ViewBag.Data.Email</h3>
            @ViewBag.Data.Content

        </div>
        <div class="modal-footer">

            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

        </div>

    </div>
    </div>