SalesMenClient/Models/Entity/UserManuals.cs
using SalesMenClient.Models.Global;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;

namespace SalesMenClient.Models.Entity
{
    public class UserManuals
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int Status { get; set; }
        public DateTime Created { get; set; }

        public IEnumerable<UserManuals> GetAll()
        {
            IEnumerable<UserManuals> data;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("UserManuals").Result;
            data = response.Content.ReadAsAsync<IEnumerable<UserManuals>>().Result;
            return data;

        }

        public UserManuals GetById(int id)
        {
            UserManuals data;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("UserManuals/" + id).Result;
            data = response.Content.ReadAsAsync<UserManuals>().Result;
            return data;
        }
    }
}

SalesMenClient/Controllers/HomeController.cs
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using PagedList;
using SalesMenClient.Models.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace SalesMenClient.Controllers
{
    public class HomeController : Controller
    {
        SalesMan saleman;
        Category category;
        Brand brand;
        Type_Product type_Product;
        Parameter parameter;
        ProductAuction productAuction;
        ProAuParameter proAuParameter;
        Auction auction;
        ProductOrder proOrder;
        Order order;
        private UserManuals userManuals;
        private CustomerSuport customerSuport;
        public static Cloudinary cloudinary;
        public const string CLOUD_NAME = "dk65dthn5";
        public const string API_KEY = "887159183214426";
        public const string API_SECRET = "4ihijjYSSMO6hBARbJ05lb4k8Ek";
        Account account = new Account(CLOUD_NAME, API_KEY, API_SECRET);
        public HomeController()
        {
            saleman         = new SalesMan();
            category        = new Category();
            brand           = new Brand();
            type_Product    = new Type_Product();
            parameter       = new Parameter();
            productAuction  = new ProductAuction();
            proAuParameter  = new ProAuParameter();
            auction         = new Auction();
            proOrder        = new ProductOrder();
            order           = new Order();
            userManuals     = new UserManuals();
            customerSuport  = new CustomerSuport();
        }
        public ActionResult Index(int? page)
        {
            if (Session["loginSaleman"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            int _page = page ?? 1;
            int _pageSize = 20;
            var time = DateTime.Now;
            productAuction.UpProSt();
            var dataPro = productAuction.GetAll().Where(x => x.Status == 1);
            foreach(var item in dataPro)
            {
                if(item.EndDateTime <= time)
                {
                    UpdateStatusPro(item.ID);
                }
            }

            var dataAutionAll = auction.GetListAllBySale((Session["loginSaleman"]as SalesMan).ID);
            ViewBag.AutionAll = dataAutionAll.OrderByDescending(x => x.Created).ToPagedList(_page, _pageSize);
            var dataOrder = proOrder.GetListPOBySalesMan((Session["loginSaleman"] as SalesMan).ID).OrderBy(x => x.Order.Created);
            ViewBag.OrderAll = dataOrder.ToPagedList(_page, _pageSize);

            var dataProUpcomming = productAuction.GetBySaleMan((Session["loginSaleman"] as SalesMan).ID).Where(x => x.Status == 1);
            ViewBag.ProUpcomming = dataProUpcomming.Count();
            ViewBag.OrderSt = dataOrder.Where(x => x.Order.status == 1).Count();
            return View();
        }


        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(FormCollection form)
        {
            try
            {
                SalesMan s = new SalesMan();
                s.Email = form["email"];
                s.FullName = form["fullname"];
                s.PhoneNumber = form["phonenumber"];
                s.CMND = form["cmnd"];
                s.Address = form["address"];
                s.Password = GETSHA(form["password"]);
                s.Created = DateTime.Now;
                s.Status = 1;
                s.Rate = 0;
                 var data = saleman.AddNew(s);
                if(data.StatusCode==200)
                {
                    TempData["Success"] = "Successfully register..!";
                    return RedirectToAction("Login");
                }
                else
                {
                    TempData["Errors"] = "Register failed..!";
                    return RedirectToAction("Login");

                }
            }
            catch
            {
                TempData["Errors"] = "Register failed1..!";
                return RedirectToAction("Register");
            }
        }


        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(FormCollection form)
        {
            var data = saleman.GetAll();
            foreach(var item in data)
            {
                if(item.Email == form["email"] && item.Password == GETSHA(form["password"]))
                {
                    SalesMan s = item;
                    Session["loginSaleman"] = s;
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login");
        }
        public ActionResult Logout()
        {
            Session["loginSaleman"] = null;
            return RedirectToAction("Index");
        }
        
        //quan tri don hang
        public ActionResult MyOrder(int id,int? page)
        {
            if (Session["loginSaleman"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            int _page = page ?? 1;
            int _pageSize = 20;
            var data = proOrder.GetListPOBySalesMan(id).OrderBy(x => x.Order.Created);
            ViewBag.OrderAll = data.ToPagedList(_page,_pageSize);
            ViewBag.Order0 = data.Where(x => x.Order.status == 0).ToPagedList(_page, _pageSize);
            ViewBag.Order1 = data.Where(x => x.Order.status == 1).ToPagedList(_page, _pageSize);
            ViewBag.Order2 = data.Where(x => x.Order.status == 2).ToPagedList(_page, _pageSize);
            ViewBag.Order3 = data.Where(x => x.Order.status == 3).ToPagedList(_page, _pageSize);
            ViewBag.Order4 = data.Where(x => x.Order.status == 4).ToPagedList(_page, _pageSize);

            ViewBag.Order0Count = data.Where(x => x.Order.status == 0).Count();
            ViewBag.Order1Count = data.Where(x => x.Order.status == 1).Count();
            ViewBag.Order2Count = data.Where(x => x.Order.status == 2).Count();
            ViewBag.Order3Count = data.Where(x => x.Order.status == 3).Count();
            return View();
        }
        //chi tiet don hang
        public ActionResult OrderDetail(int id)
        {
            var data = order.GetByOrderID(id);
            ViewBag.Detail = data;
            return PartialView("_OrderDetail");
        }

        public ActionResult MyBids(int id)
        {
            ViewBag.Category = category.GetAll().Where(x =>x.Status ==1);
            ViewBag.Brand = brand.GetAll().Where(x => x.Status == 1);
            ViewBag.TypePro = type_Product.GetAll().Where(x => x.Status == 1);
            ViewBag.ProUpcomming = productAuction.GetBySaleMan(id).Where(x => x.Status==1);
            ViewBag.dataAuction = auction.GetAll().OrderByDescending(x=>x.Price);

            //san phẩm đã hết giờ
            ViewBag.ProductPass = productAuction.GetBySaleMan(id).Where(x => x.Status == 2||x.Status==3||x.Status==4||x.Status==5);
            ViewBag.ProUpcoming = productAuction.GetBySaleMan(id).Where(x => x.Status == 0);

            return PartialView("MyBids");
        }
        public ActionResult PersonalProfile(int id)
        {
            ViewBag.profile = saleman.GetById(id);
            return PartialView("_PersonalProfile");
        }
        public ActionResult AddProduct(int id)
        {
            if (Session["loginSaleman"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            ViewBag.Category = category.GetAll().Where(x => x.Status == 1);
            ViewBag.Brand = brand.GetAll().Where(x => x.Status == 1);
            ViewBag.TypePro = type_Product.GetAll().Where(x => x.Status == 1);
            return View();
        }

        public ActionResult GetPramByID(int type_id)
        {
            ViewBag.Parameter = parameter.GetByType(type_id).Where(x=>x.Status==1);
            ViewBag.Brand = brand.GetAll().Where(x => x.TypeProID == type_id).Where(x => x.Status == 1);
            return PartialView("_GetPramByID");
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddProduct(FormCollection form,string[] param_id,string[] value_param,string[] param_name, HttpPostedFileBase file)
        {
            if (Session["loginSaleman"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            ProductAuction proAu = new ProductAuction();
            cloudinary = new Cloudinary(account);
            string _File = "";
            string _FileName = "";
            string _path = "";
            try
            {
                DateTime startDT = DateTime.Parse(form["datestart"] + " " + form["timestart"]);
                DateTime endDT = DateTime.Parse(form["dateend"] + " " + form["timeend"]);

                if(startDT>=endDT)
                {
                    TempData["Errors"] = "The starting time must be less than the end time..!";
                    return RedirectToAction("AddProduct");
                }

            if (file.ContentLength > 0)
            {
                _File = Path.GetFileName(file.FileName);
                _FileName = _File;
                _path = Path.Combine(Server.MapPath("~/Assets/uploads"), _FileName);
                file.SaveAs(_path);
                var uploadParams = new ImageUploadParams()
                {
                    File = new FileDescription(_path),

                };
                var uploadResult = cloudinary.Upload(uploadParams);

SalesMenClient/Controllers/ProductAutionController.cs
using SalesMenClient.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SalesMenClient.Controllers
{
    public class ProductAutionController : Controller
    {

        ProductAuction productAuction;
        Auction auction;
        ProAuParameter proAuParameter;
        Brand brand;
        Order order;

        public ProductAutionController()
        {
            productAuction  = new ProductAuction();
            auction         = new Auction();
            proAuParameter  = new ProAuParameter();
            brand           = new Brand();
            order           = new Order();
        }
        // GET: ProductAution
        public ActionResult Detail(int id)
        {
            if (Session["loginSaleman"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            var data = productAuction.GetById(id);
            ViewBag.Brand = brand.GetById(data.BrandID);
            ViewBag.DetailProAuction = data;
            var dataAuction = auction.GetByProduct(id);
            if (dataAuction.Count() == 0)
            {
                ViewBag.ProAuction = null;
            }
            else
            {
                ViewBag.ProAuction = dataAuction.OrderByDescending(x => x.Created).First();


            }
            var dataParamPro = proAuParameter.GetProAu(id);
            ViewBag.Parameter = dataParamPro;
            var dataAuctionAll = auction.GetList(id).OrderByDescending(x => x.Created);
            ViewBag.ProAuctionAll = dataAuctionAll;
            ViewBag.TotalAution = dataAuctionAll.Count();

            return View();
        }
        public ActionResult CheckOrder(int id)
        {
            ViewBag.Detail = order.GetOrderByAucID(id);
            return PartialView("CheckOrder");
        }
    }
}

SalesMenClient/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SalesMenClient/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SalesMenClient/Views/Home/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@using SalesMenClient.Models.Entity
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

<div class="cart-sidebar-area">
    <div class="top-content">
        <a href="index.html" class="logo">
            <img src="~/Assets/assets/images/logo/logo2.png" alt="logo">
        </a>
        <span class="side-sidebar-close-btn"><i class="fas fa-times"></i></span>
    </div>
    <div class="bottom-content">

    </div>
</div>

<div class="hero-section style-2">
    <div class="container">
        <ul class="breadcrumb">
        </ul>
    </div>
    <div class="bg_img hero-bg bottom_center" data-background="https://localhost:44300/Assets/assets/images/banner/hero-bg.png" style="        background-image: url(&quot;https://localhost:44300/Assets/assets/images/banner/hero-bg.png&quot;);"></div>
</div>

<section class="dashboard-section padding-bottom mt--240 mt-lg--440 pos-rel">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-10 col-md-7 col-lg-4">
                <div class="dashboard-widget mb-30 mb-lg-0 sticky-menu">
                    <div class="user">
                        <div class="thumb-area">
                            <div class="thumb">
                                <img src="~/Assets/assets/images/dashboard/user.png" alt="user">
                            </div>
                            <label for="profile-pic" class="profile-pic-edit"><i class="flaticon-pencil"></i></label>
                            <input type="file" id="profile-pic" class="d-none">
                        </div>
                        <div class="content">
                            <h5 class="title"><a href="#0">@((Session["loginSaleman"] as SalesMan).FullName)</a></h5>
                            <span class="username">@((Session["loginSaleman"] as SalesMan).Email)</span>
                        </div>
                    </div>
                    <ul class="dashboard-menu">
                        <li>
                            <a href="javascript:void(0)" onclick="Dasboarh()"><i class="flaticon-dashboard"></i>Dashboard</a>
                        </li>
                        <li>
                            <a href="javascript:void(0)" onclick="Profile(@((Session["loginSaleman"] as SalesMan).ID))"><i class="flaticon-settings"></i>Personal Profile </a>
                        </li>
                        <li>
                            <a href="javascript:void(0)" onclick="MyBils(@((Session["loginSaleman"] as SalesMan).ID))"><i class="flaticon-auction"></i>My Bids</a>
                        </li>
                        <li>
                            <a href="@Url.Action("MyOrder",new { id =  (Session["loginSaleman"] as SalesMan).ID })"><i class="flaticon-auction"></i>My Order</a>
                        </li>
                        <li>
                            <a href="@Url.Action("AddProduct","Home",new {id = (Session["loginSaleman"] as SalesMan).ID })"><i class="flaticon-shake-hand"></i>Create a new auction</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Logout","Home")"><i class="fas fa-sign-out-alt" style="font-weight:0 !important;"></i>Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class=" col-lg-8" id="content-saleman">
                <div class="dashboard-widget mb-40">
                    <div class="dashboard-title mb-30">
                        <h5 class="title">My Activity</h5>
                    </div>
                    <div class="row justify-content-center mb-30-none">
                        <div class="col-md-6 col-sm-6">
                            <div class="dashboard-item">
                                <div class="thumb">
                                    <img src="~/Assets/assets/images/dashboard/01.png" alt="dashboard">
                                </div>
                                <div class="content">
                                    <h2 class="title"><span class="counter">@ViewBag.ProUpcomming</span></h2>
                                    <h6 class="info">Active Product Auction</h6>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="dashboard-item">
                                <div class="thumb">
                                    <img src="~/Assets/assets/images/dashboard/02.png" alt="dashboard">
                                </div>
                                <div class="content">
                                    <h2 class="title"><span class="counter">@ViewBag.OrderSt</span></h2>
                                    <h6 class="info">Orders waiting for delivery</h6>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
                <div class="dashboard-widget">
                    <h5 class="title mb-10">Dashboard</h5>
                    <div class="dashboard-purchasing-tabs">
                        <ul class="nav-tabs nav">
                            <li>
                                <a href="#current" class="active" data-toggle="tab">Auction</a>
                            </li>
                            <li>
                                <a href="#pending" data-toggle="tab">My Order</a>
                            </li>

                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane show active fade" id="current">
                                <table class="purchasing-table">
                                    <thead>
                                        <tr>
                                            <th>Item</th>
                                            <th>Customer name</th>
                                            <th>Bid</th>

                                            <th>Expires</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var itemAu in ViewBag.AutionAll)
                                        {
                                            <tr>
                                                <td data-purchase="item"><a style="color:#000;" href="@Url.Action("Detail","ProductAution",new { id= itemAu.ProductAuction.ID})">@itemAu.ProductAuction.ID</a> </td>
                                                <td data-purchase="highest bid">@itemAu.Customer.FullName</td>
                                                <td data-purchase="bid price">$@Convert.ToDecimal(itemAu.Price).ToString("#,##0.0")</td>
                                                <td data-purchase="expires">@itemAu.Created</td>
                                            </tr>
                                        }


                                    </tbody>
                                </table>
                            </div>
                            <div class="tab-pane show fade" id="pending">
                                <table class="purchasing-table">
                                    <thead>
                                        <tr>
                                            <th>Order</th>
                                            <th>Product</th>
                                            <th>Total Price</th>
                                            <th>Status</th>
                                           
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var order in ViewBag.OrderAll)
                                        {
                                            <tr>
                                                <td data-purchase="item">@order.Order.ID</td>
                                                <td data-purchase="bid price">@order.ProductAuction.ID</td>
                                                <td data-purchase="highest bid">$@Convert.ToDecimal(order.Order.TotalPrice).ToString("#,##0.0")</td>
                                                @{
                                                    Order od = new Order();
                                                    var st_value = od.OrderSt(order.Order.status);
                                                    var st_class = od.OrderStClass(order.Order.status);
                                                }
                                                <td data-purchase="lowest bid"><span class="@st_class">@st_value</span></td>
                                               
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                    @Html.PagedListPager((IPagedList)ViewBag.OrderAll, page => Url.Action("Index", new { id = (Session["loginSaleman"] as SalesMan).ID, page }))
                </div>
            </div>
        </div>
    </div>
</section>
@section scripts {
    <script>

         $(function () {
                    var sss = '@TempData["Success"]';
                    var err = '@TempData["Errors"]';
                    console.log(sss);
             if (sss != '') {
                
                    swal(sss, "Hãy xác nhận để tiếp tục!", "success");
                    }
             if (err != '') {
                 
                    swal(err, "...and here's the text!");
             }

         })
        function MyBils(id) {
            $.ajax({
                type: 'GET',
                url: 'Home/MyBids/' + id,
                success: function (res) {
                    $("#content-saleman").html(res);
                }
            })
        }
        function MyOrder(id) {
            $.ajax({
                type: 'GET',
                url: 'Home/MyOrder/' + id,
                success: function (res) {
                    $("#content-saleman").html(res);
                }
            })
        }
        function Profile(id) {
            $.ajax({
                type: 'GET',
                url: 'Home/PersonalProfile/' + id,
                success: function (res) {
                    $("#content-saleman").html(res);
                }
            })
        }
        function Dasboarh() {
            $.ajax({
                type: 'GET',
                url: '@Url.Action("Index","Home")',
                success: function () {
                    location.reload();
                }
            })
        }
    </script>
}

SalesMenClient/Views/Home/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

<div class="cart-sidebar-area">
    <div class="top-content">
        <a href="index.html" class="logo">
            <img src="~/Assets/assets/images/logo/logo2.png" alt="logo">
        </a>
        <span class="side-sidebar-close-btn"><i class="fas fa-times"></i></span>
    </div>
    <div class="bottom-content">
        <div class="cart-products">
            <h4 class="title">Shopping cart</h4>
            <div class="single-product-item">
                <div class="thumb">
                    <a href="#0"><img src="~/Assets/assets/images/shop/shop01.jpg" alt="shop"></a>
                </div>
                <div class="content">
                    <h4 class="title"><a href="#0">Color Pencil</a></h4>
                    <div class="price"><span class="pprice">$80.00</span> <del class="dprice">$120.00</del></div>
                    <a href="#" class="remove-cart">Remove</a>
                </div>
            </div>
            <div class="single-product-item">
                <div class="thumb">
                    <a href="#0"><img src="~/Assets/assets/images/shop/shop02.jpg" alt="shop"></a>
                </div>
                <div class="content">
                    <h4 class="title"><a href="#0">Water Pot</a></h4>
                    <div class="price"><span class="pprice">$80.00</span> <del class="dprice">$120.00</del></div>
                    <a href="#" class="remove-cart">Remove</a>
                </div>
            </div>
            <div class="single-product-item">
                <div class="thumb">
                    <a href="#0"><img src="~/Assets/assets/images/shop/shop03.jpg" alt="shop"></a>
                </div>
                <div class="content">
                    <h4 class="title"><a href="#0">Art Paper</a></h4>
                    <div class="price"><span class="pprice">$80.00</span> <del class="dprice">$120.00</del></div>
                    <a href="#" class="remove-cart">Remove</a>
                </div>
            </div>
            <div class="single-product-item">
                <div class="thumb">
                    <a href="#0"><img src="~/Assets/assets/images/shop/shop04.jpg" alt="shop"></a>
                </div>
                <div class="content">
                    <h4 class="title"><a href="#0">Stop Watch</a></h4>
                    <div class="price"><span class="pprice">$80.00</span> <del class="dprice">$120.00</del></div>
                    <a href="#" class="remove-cart">Remove</a>
                </div>
            </div>
            <div class="single-product-item">
                <div class="thumb">
                    <a href="#0"><img src="~/Assets/assets/images/shop/shop05.jpg" alt="shop"></a>
                </div>
                <div class="content">
                    <h4 class="title"><a href="#0">Comics Book</a></h4>
                    <div class="price"><span class="pprice">$80.00</span> <del class="dprice">$120.00</del></div>
                    <a href="#" class="remove-cart">Remove</a>
                </div>
            </div>
            <div class="btn-wrapper text-center">
                <a href="#0" class="custom-button"><span>Checkout</span></a>
            </div>
        </div>
    </div>
</div>
<div class="hero-section">
    <div class="container">
        <ul class="breadcrumb">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>
                <a href="#0">Pages</a>
            </li>
            <li>
                <span>Sign In</span>
            </li>
        </ul>
    </div>
    <div class="bg_img hero-bg bottom_center" data-background="https://localhost:44303/Assets/assets/images/banner/hero-bg.png" style="background-image: url(&quot;assets/images/banner/hero-bg.png&quot;);"></div>
</div>

<section class="account-section padding-bottom">
    <div class="container">
        <div class="account-wrapper mt--100 mt-lg--440">
            <div class="left-side">
                <div class="section-header">
                    <h2 class="title">HI, THERE</h2>
                    <p>You can log in to your Sbidu account here.</p>
                </div>

                @using (Html.BeginForm("Login", "Home", FormMethod.Post, new { @Class = "login-form" }))
                {
                    <div class="form-group mb-30">
                        <label for="login-email"><i class="far fa-envelope"></i></label>
                        <input type="text" id="login-email" name="email" placeholder="Email Address">
                    </div>
                    <div class="form-group">
                        <label for="login-pass"><i class="fas fa-lock"></i></label>
                        <input type="password" name=password id="login-pass" placeholder="Password">
                        <span class="pass-type"><i class="fas fa-eye"></i></span>
                    </div>
                    <div class="form-group">
                        <a href="#0">Forgot Password?</a>
                    </div>
                    <div class="form-group mb-0">
                        <button type="submit" class="custom-button">LOG IN</button>
                    </div>
                }
            </div>
            <div class="right-side cl-white">
                <div class="section-header mb-0">
                    <h3 class="title mt-0">NEW HERE?</h3>
                    <p>Sign up and create your Account</p>
                    <a href="@Url.Action("Register","Home")" class="custom-button transparent">Sign Up</a>
                </div>
            </div>
        </div>
    </div>
</section>
@section scripts {
    <script>
         $(function () {
                    var sss = '@TempData["Success"]';
                    var err = '@TempData["Errors"]';
                    console.log(sss);
             if (sss != '') {
                 alert(sss);
                    swal(sss, "Hãy xác nhận để tiếp tục!", "success");
                    }
             if (err != '') {
                 alert(err);
                    swal(err, "...and here's the text!");
                    }
         })
    </script>
}