AdminOnlineAuction/Controllers/ProductAuctionController.cs
using AdminOnlineAuction.Common;
using AdminOnlineAuction.Models.Entity;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminOnlineAuction.Controllers
{
    public class ProductAuctionController : Controller
    {

        private ProductAuction productAuction;
        private Auction auctions;
        private Order order;
        public ProductAuctionController()
        {
            productAuction = new ProductAuction();
            auctions = new Auction();
            order = new Order();
        }

        // GET: ProductAuction
        public ActionResult Index(int? page, int? key,int? date)
        {
            if (Session["loginAdmin"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            productAuction.UpdateStSuccessPro(3);
            int _page = page ?? 1;
           
            int _pageSize = 10;
            int _key = key ?? 0;
            int _date = date ?? 0;
            var dataPro = productAuction.GetProAll().OrderByDescending(x => x.EndDateTime);
            

            if(_key != 0)
            {
                if(_date != 0)
                {ViewBag.ProductAuction1 = dataPro.Where(x => x.ID == key && x.EndDateTime.Month==date).ToPagedList(_page, _pageSize);}
                else
                {ViewBag.ProductAuction1 = dataPro.Where(x => x.ID == key).ToPagedList(_page, _pageSize);}
            }
            else
            {
                if(_date != 0)
                {ViewBag.ProductAuction1 = dataPro.Where(x=> x.EndDateTime.Month == date).ToPagedList(_page, _pageSize);}
                else
                {ViewBag.ProductAuction1 = dataPro.ToPagedList(_page, _pageSize);}
            }


            ViewBag.StatusAll = dataPro.Count();
            ViewBag.Status0 = productAuction.CoutPro(0);
            ViewBag.Status1 = productAuction.CoutPro(1);
            ViewBag.Status2 = productAuction.CoutPro(2)+ productAuction.CoutPro(3)+ productAuction.CoutPro(4)+ productAuction.CoutPro(5);
            /*ViewBag.Status3 = productAuction.CoutPro(3);
            ViewBag.Status4 = productAuction.CoutPro(4);*/
            ViewBag.Date = _date;
            ViewBag.Key = _key;
            return View();
        }
        public ActionResult GetAction2(int status,int? page,int? key, int? date)
        {
            int _page = page ?? 1;
            int _pageSize = 10;
            int _key = key ?? 0;
            var dataPro = productAuction.GetProAll();
            int _date = date ?? 0;
            if (_key!=0)
            {
                if(status==2)
                {
                    if(_date!=0)
                    {
                        ViewBag.ProductAuction1 = dataPro.Where(x => x.Status == status || x.Status == 3 || x.Status == 4 || x.Status == 5 && x.ID == key&&x.EndDateTime.Month==_date).OrderByDescending(x => x.EndDateTime).ToPagedList(_page, _pageSize);

                    }
                    else
                    {
                        ViewBag.ProductAuction1 = dataPro.Where(x => x.Status == status || x.Status == 3 || x.Status == 4 || x.Status == 5 && x.ID == key).OrderByDescending(x => x.EndDateTime).ToPagedList(_page, _pageSize);

                    }
                }
                else
                {
                    if(_date!=0)
                    {
                        ViewBag.ProductAuction1 = dataPro.Where(x => x.Status == status && x.ID == key && x.EndDateTime.Month==_date).OrderByDescending(x => x.EndDateTime).ToPagedList(_page, _pageSize);

                    }
                    else
                    {
                        ViewBag.ProductAuction1 = dataPro.Where(x => x.Status == status && x.ID == key).OrderByDescending(x => x.EndDateTime).ToPagedList(_page, _pageSize);

                    }
                }
            }
            else
            {
                if(status==2)
                {
                    if(_date!=0)
                    {
                        ViewBag.ProductAuction1 = dataPro.Where(x => x.Status == status || x.Status == 3 || x.Status == 4 || x.Status == 5&&x.EndDateTime.Month==_date).OrderByDescending(x => x.EndDateTime).ToPagedList(_page, _pageSize);

                    }
                    else
                    {
                        ViewBag.ProductAuction1 = dataPro.Where(x => x.Status == status || x.Status == 3 || x.Status == 4 || x.Status == 5).OrderByDescending(x => x.EndDateTime).ToPagedList(_page, _pageSize);

                    }
                }
                else
                {
                    if(_date!=0)
                    {
                        ViewBag.ProductAuction1 = dataPro.Where(x => x.Status == status&&x.EndDateTime.Month==_date).OrderByDescending(x => x.EndDateTime).ToPagedList(_page, _pageSize);

                    }
                    else
                    {
                        ViewBag.ProductAuction1 = dataPro.Where(x => x.Status == status).OrderByDescending(x => x.EndDateTime).ToPagedList(_page, _pageSize);

                    }
                }
            }

            ViewBag.StatusPresent = status;
            ViewBag.Status0 = productAuction.CoutPro(0);
            ViewBag.Status1 = productAuction.CoutPro(1);
            ViewBag.Status2 = productAuction.CoutPro(2) + productAuction.CoutPro(3) + productAuction.CoutPro(4) + productAuction.CoutPro(5);
            ViewBag.Date = _date;
            ViewBag.Key = _key;
            ViewBag.StatusAll = dataPro.Count();
            return View();
        }
        public ActionResult Detail(int id)
        {
            ViewBag.Detail = productAuction.GetProByID(id);
            return PartialView("_Detail");
        }

       
        //check ai la nguoi chien thang roi tao don
        public ActionResult CreateOrder(int proid)
        {
            ViewBag.ProAuction = productAuction.ProductByID(proid);
            ViewBag.Auction = auctions.GetListByPro(proid).OrderByDescending(x=>x.Created);
            return View();
        }
        //check don hang
        public ActionResult CheckOrder(int id)
        {
         
            var data = order.OrderByAutionID(id);
            ViewBag.Data = data;
            ViewBag.Pro = order.GetAutionByProId(data.AutionID);
            return PartialView("_CheckOrder");
        }

        public ActionResult CheckAuStatus(int auid,int status)
        {
            var auData = auctions.GetById(auid);
            var data = auctions.GetListByPro(auData.ProAutionID);
            foreach(var item in data)
            {
                if(item.ID != auData.ID)
                {
                    item.Status = 2;
                    auctions.Edit(item);
                }
            }

            auData.Status = status;
            auctions.Edit(auData);
            

            TempData["Success"] = "Successful confirmation..!";
            return RedirectToAction("CreateOrder", new { proid = auData.ProAutionID });
        }
       
        public ActionResult CreateOrders(int auid)
        {
            var date_time_now = DateTime.Now;
            var data = auctions.GetAcByID(auid);
            data.Status = 3;
            auctions.Edit(data);
            Order oderNew = new Order();
            oderNew.CustomerID = data.CustomerID;
            oderNew.ProAutionID = data.ProAutionID;
            oderNew.Created = date_time_now;
            oderNew.EndDateTime = date_time_now.AddDays(1);
            oderNew.AutionID = data.ID;
            oderNew.status = 0;
            oderNew.TotalPrice = data.Price;
            var aucfee = (data.Price * 5) / 100;
            var moneyRece = data.Price - aucfee;
            oderNew.AuctionFees = aucfee;
            oderNew.MoneyReceived = moneyRece;
            var orderData = order.AddNew(oderNew);

            string content2 = System.IO.File.ReadAllText(Server.MapPath("~/Assets/Template/neworder2.html"));
            string contentmail = "Congratulations on your successful order,We have received the order, will contact you as soon as possible...";
            if (orderData.StatusCode==200)
            {
                //content 2
               /* content2 = content2.Replace("{{Image}}", data.ProductAuction.Image);
                content2 = content2.Replace("{{ProName}}", data.ProductAuction.ProName);
                content2 = content2.Replace("{{ProCode}}", Convert.ToString(data.ProductAuction.ID));
                content2 = content2.Replace("{{Email}}", oderNew.Email);
                content2 = content2.Replace("{{ContentVl}}", contentmail);
                content2 = content2.Replace("{{Phone}}", oderNew.Phone);
                content2 = content2.Replace("{{Note}}", Convert.ToString(data.ID));
                content2 = content2.Replace("{{Fullname}}", oderNew.Receiver);
                content2 = content2.Replace("{{pathToFile}}", "https://res.cloudinary.com/dk65dthn5/image/upload/v1611217961/logo2_lidt9c.png");
                content2 = content2.Replace("{{Total}}", oderNew.TotalPrice.ToString("N0"));
                var toEmail2 = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();

                new MailHelper().SendMail2(oderNew.Email, "Đơn hàng mới từ OnlineShop", content2);
                new MailHelper().SendMail2(toEmail2, "Đơn hàng mới từ OnlineShop", content2);*/
                TempData["Success"] = "Successfully created an order..!";
                return RedirectToAction("CreateOrder", new { proid = data.ProAutionID });
            }
            else
            {
                TempData["errors"] = "Create a failed order..!";
                return RedirectToAction("CreateOrder", new { proid = data.ProAutionID });
            }
        }
    }
}

AdminOnlineAuction/Views/ProductAuction/CreateOrder.cshtml
@{
    ViewBag.Title = "CreateOrder";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Auction</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Auction</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="callout callout-info">
                    <h5><i class="fas fa-info"></i> Note:</h5>
                    This is a list of auction participants.
                </div>


                <!-- Main content -->
                <div class="invoice p-3 mb-3">
                    <!-- title row -->
                    <div class="row">
                        <div class="col-12">
                            <h4>
                                <i class="fas fa-globe"></i> @ViewBag.ProAuction.ProName.

                            </h4>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- info row -->
                    <div class="row invoice-info">
                        <div class="col-sm-4 invoice-col">
                            <address>
                                <strong>Product Name:  @ViewBag.ProAuction.ProName </strong><br>
                                Start Date Time: @ViewBag.ProAuction.StartDateTime <br>
                                End Date Time: @ViewBag.ProAuction.EndDateTime <br>
                                Category:  @ViewBag.ProAuction.Category.CateName <br>

                            </address>
                        </div>
                        <!-- /.col -->

                    </div>
                    <!-- /.row -->
                    <!-- Table row -->
                    <div class="row">
                        <div class="col-12 table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>User Name</th>
                                        <th>Giờ đặt</th>
                                        <th>Số tiền</th>
                                        <th>Trạng thái</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{int i = 0;}
                                    @foreach (var auction in ViewBag.Auction)
                                    {
                                        <tr>
                                            <td>@{i++;} @i</td>
                                            <td>@auction.Customer.Email</td>
                                            <td>@auction.Created</td>
                                            <td>$@Convert.ToDecimal(auction.Price).ToString("#,##0.0")</td>
                                            @if (auction.Status == 1 || auction.Status == 3)
                                            {
                                                <td><p class="badge badge-success">Chiến thắng</p></td>
}
                                            else if (auction.Status == 2)
                                            {
                                                <td><p class="badge badge-danger">Thất bại</p></td>
}
                                            else
                                            {
                                                <td><p class="badge badge-primary">Đang chờ</p></td>
}
                                            <td>
                                                @if (auction.Status == null || auction.Status == 0)
                                                {
                                                    <a class="btn btn-primary" href="@Url.Action("CheckAuStatus","ProductAuction",new { auid = auction.ID,status = 1 })" style="color:#fff"><i class="fas fa-check" style="padding-right:5px"></i> xác nhận thắng</a>
                                                }
                                                else if (auction.Status == 1)
                                                {
                                                    <a class="btn btn-primary" href="@Url.Action("CreateOrders","ProductAuction",new { auid = auction.ID })" style="color:#fff">Tạo đơn</a>
                                                }
                                                else if (auction.Status == 2)
                                                {

                                                }
                                                else if (auction.Status == 3)
                                                {
                                                    <p class="badge badge-info">Tạo đơn thành công</p>
                                                    <p class="badge badge-info" onclick="DetailPro(@auction.ID)" type="button" data-toggle="modal" data-target="#modal-default">Check đơn</p>
                                                }

                                            </td>
                                        </tr>
                                    }


                                </tbody>
                            </table>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->


                </div>
                <!-- /.invoice -->
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</section>

<div class="modal fade" id="modal-default" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="modal-detail" style="width:700px;">
            <div class="modal-header">
                <h4 class="modal-title">Default Modal</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <p>One fine body…</p>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@section scripts {
    <script>
        function DetailPro(id) {
            $.ajax({
                type: 'GET',
                url: '../ProductAuction/CheckOrder/' + id,
                success: function (res) {
                    $("#modal-detail").html(res);
                }
            })
        }
    </script>

}

AdminOnlineAuction/Views/ProductAuction/GetAction2.cshtml
@using PagedList;
@using PagedList.Mvc;
@using AdminOnlineAuction.Models.Entity;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Product auction manager</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Product auction manager</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Product auction manager</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0 mt-3 mb-3">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-2">
                        <a href="@Url.Action("Index","ProductAuction")" class="btn btn-block btn-primary">All(@ViewBag.StatusAll)</a>
                    </div>
                    <div class="col-md-2">
                        <a href="@Url.Action("GetAction2","ProductAuction",new { status = 1 })" class="btn btn-block btn-info">Active(@ViewBag.Status1)</a>
                    </div>
                    <div class="col-md-2">
                        <a href="@Url.Action("GetAction2","ProductAuction",new { status = 2 })" class="btn btn-block btn-warning">End(@ViewBag.Status2)</a>
                    </div>
                    <div class="col-md-2">
                        <a href="@Url.Action("GetAction2","ProductAuction",new { status = 0 })" class="btn btn-block btn-secondary">Upcoming(@ViewBag.Status0)</a>
                    </div>
                    <div class="col-md-2">
                        @*<a href="@Url.Action("GetAction2","ProductAuction",new { status = 3 })" class="btn btn-block btn-success">Success(@ViewBag.Status3)</a>*@

                    </div>
                    <div class="col-md-2">
                        @*<a href="@Url.Action("GetAction2","ProductAuction",new { status = 4 })" class="btn btn-block btn-danger">Failure(@ViewBag.Status4)</a>*@

                    </div>
                    <div class="col-md-8">
                        @using (Html.BeginForm())
                        {
                            <label class="col-form-label" for="inputWarning">
                                <i class="far fa-bell"></i> search by product code
                            </label>
                            <div class="row">

                                <div class="col-md-8">
                                    <div class="row">
                                        <div class="col-md-7">
                                            <div class="form-group">
                                                <input type="hidden" name="status" value="@ViewBag.StatusPresent" />
                                                <input type="number" name="key" class="form-control is-warning" id="inputWarning" placeholder="Enter product code...">
                                            </div>
                                        </div>
                                        @{
                                            ProductAuction pro = new ProductAuction();
                                        }
                                        <div class="col-md-5">
                                            <div class="form-group">
                                                <select name="date" class="form-control">
                                                    <option value="0">-- Selection End Date Time--</option>
                                                    <option value="1" @pro.CheckSelected(ViewBag.Date, 1)>January</option>
                                                    <option value="2" @pro.CheckSelected(ViewBag.Date, 2)>February</option>
                                                    <option value="3" @pro.CheckSelected(ViewBag.Date, 3)>March</option>
                                                    <option value="4" @pro.CheckSelected(ViewBag.Date, 4)>April</option>
                                                    <option value="5" @pro.CheckSelected(ViewBag.Date, 5)>May</option>
                                                    <option value="6" @pro.CheckSelected(ViewBag.Date, 6)>June</option>
                                                    <option value="7" @pro.CheckSelected(ViewBag.Date, 7)>July</option>
                                                    <option value="8" @pro.CheckSelected(ViewBag.Date, 8)>August</option>
                                                    <option value="9" @pro.CheckSelected(ViewBag.Date, 9)>September</option>
                                                    <option value="10" @pro.CheckSelected(ViewBag.Date, 10)>October</option>
                                                    <option value="11" @pro.CheckSelected(ViewBag.Date, 11)>November</option>
                                                    <option value="12" @pro.CheckSelected(ViewBag.Date, 12)>December</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    </div>
                                <div class="col-md-4">
                                    <button type="submit" class="btn btn-primary">Search</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>

        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>

<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Product auction manager</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        <th style="width: 1%">#</th>
                        <th style="width: 20%">Product Name</th>
                        <th>Image product</th>
                        <th>End date time</th>
                        <th style="width: 8%" class="text-center">Status</th>
                        <th style="width: 20%"></th>
                    </tr>
                </thead>
                <tbody>
                    @{int i = 0;}
                    @foreach (var item in ViewBag.ProductAuction1)
                    {
                        <tr>
                            <td>@{i++;} @i</td>
                            <td>
                                <a>@item.ProName</a>
                                <br>
                                <small>Created: @item.Created</small>
                                <br>
                                <small>Category: @item.Category.CateName</small>
                                <br />
                                <small>
                                    Product code: @item.ID
                                </small>
                            </td>
                            <td>
                                <img alt="Avatar" class="table-avatar" src="@item.Image">
                            </td>
                            <td>
                                @item.EndDateTime
                            </td>
                            @{
                                ProductAuction proAu = new ProductAuction();
                                var status_vl = proAu.ProAuStatus(item.Status);
                                var status_class = proAu.ClassStatus(item.Status);
                            }
                            <td class="project-state">

                                <span class="@status_class">@status_vl</span>
                            </td>
                            <td class="project-actions text-center">
                                <button class="btn btn-primary btn-sm" onclick="DetailPro(@item.ID)" type="button" data-toggle="modal" data-target="#modal-default">
                                    <i class="fas fa-folder">
                                    </i>
                                    View
                                </button>
                               
                            </td>
                        </tr>
                    }


                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
        <div class="card-footer clearfix">

            @Html.PagedListPager((IPagedList)ViewBag.ProductAuction1, page => Url.Action("GetAction2", new { page ,status= @ViewBag.StatusPresent }))

        </div>
    </div>
    <!-- /.card -->

</section>


<div class="modal fade" id="modal-default" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="modal-detail" style="width:700px;">
            <div class="modal-header">
                <h4 class="modal-title">Detail Product</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <p>One fine body…</p>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@section scripts {
    <script>
        function DetailPro(id) {
            $.ajax({
                type: 'GET',
                url: '../ProductAuction/Detail/' + id,
                success: function (res) {
                    $("#modal-detail").html(res);
                }
            })
        }
    </script>

}

AdminOnlineAuction/Views/ProductAuction/_Detail.cshtml
@using AdminOnlineAuction.Models.Entity;
<div class="modal-header">
    <h4 class="modal-title">Detail Product</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>
<div class="modal-body">
    <h3 class="text-primary"><i class="fas fa-info-circle" style="margin-right:10px">  </i>@ViewBag.Detail.ProName</h3>
    <div class="text-muted">
        <img src="@ViewBag.Detail.Image" width="150" />
    </div>
   
    <h5 class="mt-5 text-muted">Info:</h5>
    <table class="table table-striped projects">
        <tr>
            <td>Status:</td>
            @{
                ProductAuction proAu = new ProductAuction();
                var status_vl = proAu.ProAuStatus(ViewBag.Detail.Status);
                var status_class = proAu.ClassStatus(ViewBag.Detail.Status);
            }
            <td>

                <p class="@status_class">@status_vl</p>
            </td>
        </tr>
        <tr>
            <td>Date Created:</td>
            <td>@ViewBag.Detail.Created</td>
        </tr>
        <tr>
            <td>Start date time:</td>
            <td>@ViewBag.Detail.StartDateTime</td>
        </tr>
        <tr>
            <td>End date time:</td>
            <td>@ViewBag.Detail.EndDateTime</td>
        </tr>
        <tr>
            <td>Category:</td>
            <td>@ViewBag.Detail.Category.CateName</td>
        </tr>
        <tr>
            <td>Brand:</td>
            <td>@ViewBag.Detail.Brand.BrandName</td>
        </tr>
        <tr>
            <td>Original Price:</td>
            <td>$@Convert.ToDecimal(ViewBag.Detail.OriginalPrice).ToString("#,##0.0")</td>
        </tr>
        <tr>
            <td>Price Step:</td>
            <td>$@Convert.ToDecimal(ViewBag.Detail.PriceStep).ToString("#,##0.0")</td>
        </tr>
        <tr>
            <td>Purchasing Price:</td>
            <td>$@Convert.ToDecimal(ViewBag.Detail.PurchasingPrice).ToString("#,##0.0")</td>
        </tr>
        <tr>
            <td>Salesman:</td>
            <td>@ViewBag.Detail.SalesMan.FullName</td>
        </tr>
        @if (ViewBag.Detail.Status == 2)
        {
            <tr>
                <td>Action:</td>
                <td> <a href="@Url.Action("CreateOrder","ProductAuction",new { proid = ViewBag.Detail.ID })" class="btn btn-info btn-sm mt-1">Xem danh sách đấu giá</a></td>
            </tr>


        }


    </table>
</div>
<div class="modal-footer justify-content-between">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    
</div>